title: Envian's NA Criterion Strats
description: NA Criterion Strats.
theme: just-the-docs
color_scheme: dark

enable_copy_code_button: true

url: https://criterion.envian.net/
repo: https://github.com/Envian/xiv-criterion-na-strats

aux_links:
  Criterion Discord: https://discord.gg/gX38DtbAZa
  Github: https://github.com/Envian/xiv-criterion-na-strats

nav_enabled: true
aux_links_new_tab: true

collections_dir: guides

callouts:
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: yellow
  uptime:
    title: Uptime Strategy
    color: red

collections:
  ew:
    permalink: /:path/
    output: true

just_the_docs:
  collections:
    ew:
      name: Endwalker

sass:
  quiet_deps: true
